INSERT INTO Wymaganie (Tresc, Ogloszenie_Id) VALUES
('doœwiadczenie w prowadzeniu projektów, znajomoœæ bud¿etowania, wiedza z zakresu marketingu i handlu, znajomoœæ technik kszta³towania wizerunku produktu',1210),
('znajomoœæ procedur windykacyjnych, znajomoœæ rachunkowoœci',1210),
('komunikatywnoœæ, sumiennoœæ, umiejêtnoœæ pracy w zespole, zdolnoœci organizacyjne, zdyscyplinowanie',1210),
('inicjatywa, komunikatywnoœæ, przedsiêbiorczoœæ, samodzielnoœæ, umiejêtnoœæ pracy w zespole, zdolnoœci handlowe',1210),
('inicjatywa, kreatywnoœæ, nowatorstwo, wyobraŸnia',1210),
('dok³adnoœæ, odpowiedzialnoœæ, sumiennoœæ, terminowoœæ, umiejêtnoœæ organizacji pracy, umiejêtnoœæ pracy w zespole, zdolnoœci analityczne',1210),
('empatia, komunikatywnoœæ, terminowoœæ, umiejêtnoœci interpersonalne, umiejêtnoœæ pracy w zespole, zdolnoœci organizacyjne',1210),
('zdyscyplinowanie, sumiennoœæ, uczciwoœæ, umiejêtnoœæ pracy w zespole, spostrzegawczoœæ, sprawnoœæ fizyczna, odpornoœæ na pracê monotonn¹',1210),
('cierpliwoœæ, inicjatywa, komunikatywnoœæ, ³atwoœæ w nawi¹zywaniu kontaktów, otwartoœæ',1210),
('komunikatywnoœæ, rzetelnoœæ, skrupulatnoœæ, uczciwoœæ, zdyscyplinowanie',1210),
('inicjatywa, komunikatywnoœæ, otwartoœæ, umiejêtnoœci negocjacyjne, umiejêtnoœæ pracy w zespole, zdolnoœci handlowe',1211),
('komunikatywnoœæ, myœlenie strategiczne, odpornoœæ na stres, umiejêtnoœæ zarz¹dzania ludŸmi, zdolnoœci organizacyjne',1211),
('gotowoœæ do samodzielnej i sta³ej nauki, komunikatywnoœæ, umiejêtnoœæ pracy w zespole, zdolnoœci analityczne',1211),
('komunikatywnoœæ, rzetelnoœæ, umiejêtnoœæ wspó³pracy z ludŸmi',1211),
('inicjatywa, koncentracja, organizacja pracy, praca zespo³owa, rzetelnoœæ, umiejêtnoœæ wspó³pracy z osobami z ró¿nych dzia³ów firmy, zdolnoœci analityczne',1211),
('etyka, organizacja pracy, umiejêtnoœæ wspó³pracy z osobami z ró¿nych dzia³ów firmy, umiejêtnoœæ pracy w zespole',1211),
('inicjatywa, kreatywnoœæ, nastawienie na osi¹gniêcia, umiejêtnoœæ pracy w zespole, znajomoœæ rynku',1211),
('asertywnoœæ, konsekwencja, nastawienie na osi¹gniêcia, organizacja pracy, umiejêtnoœæ podejmowania decyzji, umiejêtnoœæ wywierania wp³ywu, zdolnoœci analityczne',1211),
('obs³uga komputera, umiejêtnoœæ obs³ugi urz¹dzeñ biurowych, umiejêtnoœæ asertywnego prowadzenia rozmów telefonicznych, znajomoœæ jêzyków obcych',1211),
('potwierdzone sukcesy zawodowe, znajomoœæ bran¿y, znajomoœæ rynku',1211),
('znajomoœæ bud¿etowania, znajomoœæ rynku',1212),
('wiedza z zakresu ksiêgowoœci, prawa podatkowego, zarz¹dzania finansami, znajomoœæ ogólnych zasad rachunkowoœci oraz ewidencji ksiêgowej, w tym planu kont, umiejêtnoœæ rozumienia treœci ekonomicznej kont ksiêgowych, umiejêtnoœæ wspó³pracy z instytucjami finansowymi (ZUS, US)',1212),
('znajomoœæ prawa pracy, prawa podatkowego, technik motywacji, wiedza z zakresu zarz¹dzania',1212),
('wiedza z zakresu sprzeda¿y i marketingu, znajomoœæ bran¿y',1212),
('wiedza z zakresu sprzeda¿y i marketingu',1212),
('wiedza o zarz¹dzaniu i administracji, znajomoœæ prawa pracy, umiejêtnoœæ zarz¹dzania bud¿etem',1212),
('wiedza z zakresu informatyki, umiejêtnoœæ wspó³pracy z osobami z ró¿nych dzia³ów firmy',1212),
('bieg³a znajomoœæ jêzyka obcego, znajomoœæ s³ownictwa specjalistycznego z obszaru dzia³ania firmy',1212),
('umiejêtnoœæ zarz¹dzania informacj¹, znajomoœæ analizy finansowej',1212),
('znajomoœæ zagadnieñ prawnych i analizy finansowej',1212)